---
- job:
    name: rancher-funct
    description: |
      Run Functional tests of the driver on Rancher+OTC.
    pre-run: playbooks/pre.yaml
    run: playbooks/run.yaml
    vars:
      functest_project_name: "eu-de_zuul_rancher"
      rancher_image: rancher/rancher:v2.4.8
      python_version: 3.8
      # secrets:
      # - rancher_credentials
    nodeset:
      nodes:
        - name: rancher
          label: ubuntu-focal
    required-projects:
      - opentelekomcloud/kontainer-engine-driver-otc
      - opentelekomcloud/ui-cluster-driver-otc

- secret:
    name: rancher_credentials
    data:
      user_name: !encrypted/pkcs1-oaep
        - ZHrg13IzwMSLjFdmoa5vjZAL1I5RYQdL1+KLVxhfmjZH9J6MqPFqlAzEz73ZCE1xtFYii
          TcOHaNOdpghVIkSTLf4SSPnMN/obJs6TjQkmv1fc0HFpcpFsmVMgCfdt8iIht+NGnqkJJ
          XQm0ScsqH4bj8HKdsy3nhQw9PgH/dFRPkhHqoj+DTzkzLrZFO+++ACdmsFrOLHXquBiw/
          0CXFx8f7W5j/wQ0QLlmQyGls+UHI6NR7RY2sWT6w2XwWKyBAxHvpynSrvr6gGVfUrSBaC
          LG83SknMyBlGgi7Ol2x74WlzuXIdbUpNaxK7oSUi0SceOOWuz29z5GVn1V99RUSfcHqws
          y+2EyllJJew22kxe0vBffN4yGygG2YCxRfF7JagAh3TnHoxk0CrtJRQRu1dy79pbLV5rl
          Srp2C8bK77ZNOIsxpgGAxgtKaT7ZfXXhf8L5i2hvemLdjsJ5L3RGBDouoowLbeAK2aFhC
          psju+1/72h/Alwpn4OZcYGTud4snu2OeFQHsAxPwmaWm7lElKyJoD5GWJv/4qrCvwBSJ2
          qVYTu5yF9VBpdvpUk4tNPD9pzzZwk/+zLj4VXRcjyH99BMwkzHzc747DYaShlx4EHwQ/2
          uWWSD4A5+e3eK5+Vva/KXSlwvQNQeT/nC4aYSbpp+amDIzEmIYhy2vwHMC0FhA=
      password: !encrypted/pkcs1-oaep
        - mwjn51WR68/5IZ1UJUS5O5RSd7W/0azDnKdEDXi+uTiPIxBIw8bX/6C6Yjed8XtbQ4PLW
          vLxb8EDDYmbP3NwD/Fjl9MMZm/uSEGw5uhOF50OrelcDQT5xgZNRJMcJTSpOzikHjycks
          PnZuZxY086jvdpVOWkuoqF38htArnvw6A2dxIjq6DSO6tvcyDNQgjTjVdoNvTagVfIHjV
          DlLN7RlpCNidgb1AkvU+SRU6ZfCPZflsdvRd1blOamJMbUrfdzapKusugzomA+Z6NRB2f
          Yukj9qRpuT9tLeCzN1w1LiEpkgAcz5x9hLPyvr7cfFZ2P8w7gumt7d+nfb2IncFKz8A3M
          XHrKmQXhbbemo+y3RVREe1Gl2MN14f1TAs0lZ7HeJGt0r44FNOjRum/kaiZMx8lpwMdWk
          A4BY4jEqpV11237kZVObfntckzEIm2nmUjzUbBvAlDadPhLIqtkxA3RqInQh/amG7T/+v
          sm/9q3jHA9Kss3bGncP0FIbZzMYDqYUoVffmiLKHY5m6eJmVXJ8vdAUa6+QKll+2JFDvn
          Rj0uQEuWDkZ3KorX+4W5ZZbf/5XKPE5VvBwjFIRYNgktSPb+y7HSpW9a4g13lxJpJfyAA
          eMMCMDbXYXNedqhCi6JbOxsgZuHhuI2YJEeufr0SUDkW2+MqIuVuFuJjXKFysQ=
      project_name: !encrypted/pkcs1-oaep
        - HcUH2baheGU7UKZ8H8WRVJJOV3lt2nxdKUyyE8ajG3GwEUuExv20padU0oMH2sgR+KMq3
          aR6vXTRjCP0o8yMIVEJjyv8N5U74sJFclSJ9ASnWyfAhJ0v8JyxNBKx/lzSi33+fweGkx
          XZLU66pxKntCsiuRWH/aizxoBKHyQjUyVirm/nzqonAzqA3CF1e3JZoWKqS3Ie75l7k+U
          RmHlu6ZEJ7g3GUEjikHPAd+V0qVzJYPFOoim/KQldVSaTOIdJs5DQHEa2IOrzMmuKtZ8W
          28lSd7EjsWVyAzxdg/wlUWN9lkuwCWGEX7OpIIcAxMCJv6Jh+C/13vdX596b9TSvR/QuW
          QJXKHidB8XdysLE3MTQZFOTvhoMwaGPtBuMFeTkjl4Mr6MxE7dsTQcNXapOtJnpczTwpm
          mmcs12mOjPauPry46gZQCJCAYfpzNYJj2DvwdIsvaqsI2vX/PtfdMjXLcCrvAxmIJOTSP
          zbReQVoKy7SQuVpwEUmKekwM5YM4tr2cXwIDEVZAl5L2y8S3XwRZqEmrJJR/GbKlQig/B
          RETSNbw2Kg8zTutNtuQyW8hNEvVHxIOIb2K4yw6C8L9ZqUOCx4C6RnDGsVXqpAxFU2yPd
          MBWSdhRKdDr1Ik7o57kJ/tovnGJKfMMyzO+erJFrSx/Bkbbw0NcH0k5LK2YjdQ=
      domain_name: !encrypted/pkcs1-oaep
        - x0gTsUOk88MR6J2o9EJa+g6mok0/DUP4ncfWXNoiLjxJe10eCxJTUwJfsgT5OYRyUljW/
          1Hp0a4pvuen1ORzg8TI/VF7wBPp6NavPH0yyLu8FKKcCwLxW/VXwWhiFPbwIu96sm2PA9
          uMbVErvWkOu/Ywz+wfu63Tk6IyuRS55H27n9lVoXEfKQWE7dI51KDBF4uq4AaPP+8UTwR
          UJp1U7prP7F5qBa2Eoiex2tqBynczzJdvr6n0tuPJnUWWelZDzNR00OQF7w2Yv0qxavEp
          HdmcK3s4trGu8/cxJ9DD5/15um59k4L//VTmGPhrBmjgAu4RJZRfTEhSpA4GVg78Ood8V
          Dl5Icq8BgNRZtHhHmHxtNI9Q3JaHTLtAEKiCuGywQ/4LODCfubylIxnbKcy3Q2uLcfRU/
          nRMBA5jpjZzi2q2TQh120F+5o1p5fW2adJ3dx3alWt5vqoXFPfoEgjdP06/76kwzAeECA
          fzM3KUqdv5wStsjCzRbPbcux1TkLpu9MSEOoeTTeWk5ltwluhTSEVfLAIB3Zs9P/2VISZ
          8sM/Bc1K0bIErVYs/ZT6HJCM0udDfrS+O8OtoqvUV+j7MP2Zew/GXzp8PHF3eh8zBZTUR
          9YgmQckomtjaQVWKWy0MYt5NKj08M9oOw+1twNrw4bVR5hhf7W0GQ+68HbUhos=
      rancher_password: !encrypted/pkcs1-oaep
        - PJKqmCsLL4zXf21kp6TcuFOVcA//c21I8Xeecg0P/oy4wSg4yd1HygHUA6hhXOqlHZI1s
          4IzOFsDf4U/TTFDL0PeLjJbUtwgMl7onWYXoUNrPlQ7ob+zTd3t3OjjFYrpIUgr4X6CNM
          80zpERIXVJ5uWu38N7lssXaEb1LEWLwipZZP9JdYWDGJMZoJj+E4iWrqEp543ou9W37j2
          Gc2833SO74z6LQLILuFBbXI6xOtnonnZbOsZKKBZFsuuSKznZ74Glezaj9ncqTVn6dU9H
          jqwFDYbhCL6r1VMNjVjmd+uIdi6xsZVRbiLtb5MdKOrmKhRBFwCXKIOM+KE3HO2QwmAyw
          vI3mXiafCcHrpTLIkXkZqkY/qS15JjdOX9NAcTfoNQU3YEPlNWmOXsq+rWuCwB9V+eZUA
          27epW2ug1UdxYksSD4yB+GzxhI1ltUHlSqil5IiheI2ypIOvnOylZoYSXZPytQP5+5lPi
          nm0fbgY55ye0RnwnmKdKclwYCc9Uck3QtattMuRvgxSNEtqa3jcRgluw6hj/OwwoOVrsy
          83ruPJ2gylcACJC6g8rqeoyKFoSz55nDj0t6Tq6+xS5oNRzS0kcKxJOUa9mYZXKfBUN3R
          MLOPkNfCzwfRBE95yF/ObO4MEj7M2xB/Dd6G30VNx3Km65V28Vkc/5DIRRU/A4=

- project-template:
    name: rancher-kontainer-integration-pti
    check:
      jobs:
        - rancher-funct

- project:
    merge-mode: squash-merge
    templates:
      - rancher-kontainer-integration-pti
    vars:
      functest_project_name: "eu-de_zuul_rancher"
        #    check:
        #      jobs:
        #        - golangci-lint
        #        - golang-make-functional
        #        - golang-make-vet
        #        - goreleaser-build
        #    gate:
        #      jobs:
        #        - golangci-lint
        #        - golang-make-vet
        #        - golang-make-functional
        #        - goreleaser-build
        #    tag:
        #      jobs:
        #        - release-goreleaser

