---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - golang-make-vet
        - goreleaser-build
    gate:
      jobs:
        - golang-make-functional
        - golang-make-vet
        - goreleaser-build
    tag:
      jobs:
        - release-goreleaser