---
- hosts: all
  tasks:
    - name: Install binary dependencies
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ zuul_work_dir }}"
      when: tox_install_bindep | default(true)

- hosts: all
  roles:
    - ensure-python
    - ensure-virtualenv
    - ensure-pip
    - ensure-docker
    - ensure-goreleaser

- hosts: all
  tasks:
    - name: debug projects
      debug:
        var: zuul.projects

    - name: Build kontainer driver
      include_role:
        name: goreleaser-build
      vars:
        goreleaser_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/kontainer-engine-driver-otc'].src_dir }}"

    - name: Debug artifacts
      debug:
        var: zuul.artifacts

- hosts: all
  roles:
    - serve-artifacts
    - prepare-rancher-env

