---
- hosts: all
  tasks:
    - name: Install binary dependencies
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ zuul_work_dir }}"
      when: tox_install_bindep | default(true)

- hosts: all
  roles:
    - ensure-python
    - ensure-virtualenv
    - ensure-pip
    - ensure-docker
    - ensure-go
    - ensure-goreleaser

- hosts: all
  vars:
    artifacts_folder: "{{ ansible_user_dir }}/artifacts"
    goreleaser_project_src_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/opentelekomcloud/kontainer-engine-driver-otc'].src_dir }}"
  tasks:
    - name: debug projects
      debug:
        var: zuul.projects

    - name: Build kontainer driver
      include_role:
        name: goreleaser
      vars:
        goreleaser_args: "--snapshot --rm-dist --skip-publish --skip-sign"

    - name: Find tarballs in artifacts directory
      find:
        file_type: file
        paths: "{{ goreleaser_project_src_dir }}/dist"
        patterns: "*.tar.gz"
      register: result

    - name: Set fact for the tarball
      set_fact:
        kontainer_engine_tarball: "{{ result.files.0.path }}"

    - name: Create artifacts folder
      file:
        path: "{{ artifacts_folder }}"
        state: "directory"

    - name: Place kontainer engine content into artifacts
      copy:
        # trailing slash important
        src: "{{ kontainer_engine_tarball }}"
        dest: "{{ artifacts_folder }}"
        remote_src: true
      register: res

    - name: debug res
      debug:
        var: res

    - name: Find tarballs in artifacts directory
      find:
        file_type: file
        paths: "{{ artifacts_folder }}"
      register: result

    - name: debug artifacts
      debug:
        var: result

- hosts: all
  vars:
    artifacts_folder: "{{ ansible_user_dir }}/artifacts"
  roles:
    - serve-artifacts
    - prepare-rancher-env

